version: "3.8"
services:
  nginx:
    build:
      dockerfile: ./infrastructure/docker/nginx/Dockerfile
      context: ./
    depends_on:
      - php
  php:
    build:
      dockerfile: ./infrastructure/docker/php/Dockerfile
      context: ./
